server:
  port: 8103
spring:
  redis:
    database: 0
    host: 192.168.137.100
    port: 6379
    password: zty1993redis

# Set domain. This domain can be obtained in Java code.
website:
  domain-name: inews.com